### ISSUE TITLE
WARNING Unable to create a system terminal

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/span#12]
When SPAN is called in parallel or within galaxy process the following WARNING is showed in log file 
```
Apr 02, 2019 2:07:43 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
```

**Comment by iromeo** [comment]
Please check it again, suggested fix added. Now the warning will be shown only if help message is printed.

**Comment by olegs** [comment]
Fixed as of latest master version.
