### ISSUE TITLE
Span doesn't calculate the peak value

### ISSUE THREAD

**Issue by dievsky** [JetBrains-Research/span#15]
In theory, Span should assign each peak a value equal to its coverage score (when analyzing) or to the fold change (when comparing). However, the most basic way to launch Span (via JAR file) skips this assignment for some reason.

**Comment by dievsky** [comment]
Fixed the problem in a branch `span-peak-scores`.
Proposed approach:
- check whether the relevant coverage caches are present;
- if yes, calculate the value using the cache;
- if no, don't calculate the value (but mention it in debug info).

**Comment by dievsky** [comment]
See PR #16 .

**Comment by olegs** [comment]
PR accepted, closing the issue.
