### ISSUE TITLE
how to cite span?

### ISSUE THREAD

**Issue by clouds-drift** [JetBrains-Research/span#23]

**Comment by olegs** [comment]
Dear clouds-drift, the paper on SPAN is under review at the moment, and also we are writing technical paper now to post on arxiv.
Thank you for your interest and stay tuned!

**Comment by olegs** [comment]
Probably we should consider making source code citable till the moment we don't have paper on SPAN published, as described here: https://guides.github.com/activities/citable-code/

**Comment by olegs** [comment]
SPAN can be cited as https://www.biorxiv.org/content/10.1101/2020.05.10.087023v1
This is a preprint of the first paper introducing SPAN, we are working on a paper dedicated to SPAN itself at the moment.
