### ISSUE TITLE
Remove optional model with additional covariates from SPAN cli

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/span#26]
For the very first release version we want to eliminate as many "experimental" features as we can. 
It's okay to leave differential mode, but having two peak calling models without proper investigation of use conditions and behaviour is not good for official released version.
I suggest to introduce `SpanCLA2` for this purposes, anyone can launch it manually with full qualified name from jar file in case of need.

**Comment by dievsky** [comment]
Do you suggest duplicating the whole gargantuan `SpanCLA` file? Seems really WET.

What if we leave the regression model in `SpanCLA`, but make it "hidden"? For example, we could recognize a keyword `analyze2` (which wouldn't be shown in the help message) which would enable the regression model. This will hide the mode from the general public, but will allow as much code reuse as possible.

**Comment by olegs** [comment]
Agree, adding hidden `analyze-experimental` option will solve the problem IMO.

**Comment by olegs** [comment]
Originally I proposed to add additional class to use superclass hierarchy and override model creating from base class. This option should be considered as well to improve code readability.
