### ISSUE TITLE
Make Span file logging always set to DEBUG level

### ISSUE THREAD

**Issue by dievsky** [JetBrains-Research/span#5]
We should expect Span file logging to be consistent and independent of console logging settings.
Also, it would help us with debugging.

**Comment by olegs** [comment]
Well, actually we do have `--debug` option for SPAN, not sure that changing logging behaviour this way is really needed. If something goes wrong, we can ask user to relaunch with `--debug` option.

**Comment by olegs** [comment]
We added more information available with DEBUG log level. In case of something went wrong let's ask used to relaunch with `--debug` level.
